### PR TITLE
Upgrate gRPC to 1.13 and typescript to 2.9

### PR DESCRIPTION
**Pull request by FedeBev**
In this pull request I updated:
- gRPC to version 1.13: this version has 2 deprecation (grpc.load and addProtoService) that have been fixed
- typescript to the version 2.9: for gRPC 1.13 compatibility
- rxjs has been updated to version 6 by @kondi (rxjs6 branch - commit [e70eaa6](https://github.com/kondi/rxjs-grpc/commit/e70eaa645c617f53b1465e43c4f57d5819691b9a))

### CODE REVIEW

**Comment by ksaldana1** [comment]
Thanks for the PR @FedeBev ! I can't give you too detailed of a code review--I'll defer to @kondi there. We are using rxjs-grpc pretty heavily in our Node layer to serve as a bit of a JSON proxy/aggregator for our gRPC service layer. I have been maintaining my own fork internally (mostly for [Metadata](https://github.com/kondi/rxjs-grpc/issues/11) support).

I pulled your changes into my fork and made the various upgrades to rxjs 6 in our Node libraries. Everything worked without much issue. I will let you know if I run into any issues going forward, but for now I can serve as an additional confirmation that the upgrades are working as expected.

**Comment by kondi** [comment]
Hi!
Thanks for the contribution.

 - You can already use grpc 1.13 version, the current dependency is only a peerDependency, and only set as a minimum version (min 1.1.2). Did I miss something? I know there is a deprecation warning, but it is working.
 - Does it help something (from the user point of view) if the project is compiled with TypeScript 2.9?
 - If you need the rxjs6 support, you can use the rxjs6 prerelease version (you have actually cherry-picked from there). Its API is the same as the current 0.1.7 version except for the rxjs peerDependency upgrade.

If I would bump the grpc version requirement, it would be a breaking change, so I have to bump the major version. For the next major version I already plan to change a bit the API and I do not want to introduce multiple breaking changes separately.

**Comment by FedeBev** [comment]
- Yes, it works with warnings but I think it's bad when you use a library that introduces warnings not under your control and the 1.1 version if very very old (something like 2 years? Many improvements have been made throughout this time)

- You need a TS upgrade for some new gRPC generic functions compilation in version 1.13, maybe the 2.5 is enough but I have not tried.

- Yes, I can

What is the problem of increasing a major?
In my opinion you could do a major with rxjs6 and gRPC 1.13 and in the future a second one with the new changes you want to make. But this is only my opinion

**Comment by MOZGIII** [comment]
https://github.com/kondi/rxjs-grpc/blob/0e0f8d12fecea501d6dde35f5f90c11ade560932/package.json#L29-L37
`grpc` is actially not a peer, but a full dependency. Should probably be made peer though...

Regarding major version bumps, according to semver, pre 1.0.0 releases can be backward incompatible however they want, so just a minor bump is enough here. However, a major version bump (to 1.x.x), according to semver, would mean that this project became stable and will not break the API compatibility within the following minor/patch releases.
In either way, it's normally not up to any third-party to bump project versions, or trying to forcing it. It's simply rude, and complicates the merging of the actual useful parts of the PRs.

Overall, even though this PR made some useful changes (like bumping `grpc` version and switching to `@grpc/proto-loader` - this is a reasonable change, since relying on a deprecated API is not a good idea), it contains too much, and I'd recommend splitting it into multiple individual PRs to ease the review and merge process. That way at least some changes from this PR can be merged easily, without debating over the need to introduce them.

**Comment by alexciesielski-pioner** [comment]
Any progess on this PR? I'm in the process of working with grpc clients in my React frontend and would like to use this lib but I'm using latest TS and rxjs.

**Comment by kondi** [comment]
Released in [v0.2.0](https://github.com/kondi/rxjs-grpc/releases/tag/v0.2.0).

**Pull request closed without merging**
