### PR TITLE
feature(GrpcTypings): add forceShutdown to grpc interface

### PR DESCRIPTION
**Pull request by PatrickEifler**
First of all thanks for the nice work of this package!

The purpose of this PR is a small enhancement to the GRPC Interface.

I enhanced the typings of the GRPC interface with the forceShutdown function. This fn is provided by the native GRPC Server implementation and quite important in my use case (https://grpc.io/grpc/node/grpc.Server.html).

In addition to that I removed the DeprecationWarning - Server#addProtoService by renaming the interface and all usages to Server#addService.

@kondi Pls. let me know if you have any questions.
I'm not sure why the tests are timing out on jenkins. They are passing locally.

### CODE REVIEW

**Comment by micmro** [comment]
@kondi Any updates on this PR?

**Comment by kondi** [comment]
Thank you for the feature!
I have released version 0.1.5 with the forceShutdown function.

About the deprecation warning change, is it safe to apply? Can not break something which currently works without upgrading grpc?

**Comment by PatrickEifler** [comment]
@kondi  Thanks, glad you merged it in. 
Valid concern for the deprecation: Locally all tests passed. You can read about the deprecation in the docs: https://grpc.io/grpc/node/grpc.Server.html. I did not find much useful infos in the release notes.

**Comment by coderdiaz** [comment]
Ward.. status? :(

**Pull request closed without merging**
